{
 "title": "New York Temperature Dashboard",
 "description": "New York Temperature Dashboard",
 "time": { "from": "2024-11-30T05:00:00.000Z", "to": "2026-01-31T05:00:00.000Z" },
 "panels": [
  {
   "title": "Share of missing values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "test",
     "rawSql": "SELECT share_missing_values, \"timestamp\" FROM metrics"
    }
   ]
  },
  {
   "title": "Number of drifted columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "test",
     "rawSql": "SELECT num_drifted_cols, \"timestamp\" FROM metrics"
    }
   ]
  },
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "test",
     "rawSql": "SELECT prediction_drift, \"timestamp\" FROM metrics"
    }
   ]
  },
  {
   "title": "Mean absoulte error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "test",
     "rawSql": "SELECT mean_absolute_error, \"timestamp\" FROM metrics"
    }
   ]
  },
  {
   "title": "Root Mean Squared Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "test",
     "rawSql": "SELECT root_mean_squared_error, \"timestamp\" FROM metrics"
    }
   ]
  },
  {
   "title": "R2 Score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dataset": "test",
     "rawSql": "SELECT r2_score, \"timestamp\" FROM metrics"
    }
   ]
  }
 ]
}